#version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app/backend
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8000
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

  # mlflow:
  #   image: ghcr.io/mlflow/mlflow:v2.16.2
  #   ports:
  #     - "5000:5000"
  #   command: mlflow server --host 0.0.0.0

  # airflow:
  #   image: apache/airflow:2.10.2
  #   ports:
  #     - "8080:8080"
